version: '3.8'

services:
  # Application service for local development
  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: restaurants-api-local
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/restaurants_dev
      - JWT_SECRET=dev-jwt-secret
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
    networks:
      - restaurants-network
    command: ["npm", "run", "start:dev"]

  # PostgreSQL database for local development
  postgres:
    image: postgres:15-alpine
    container_name: restaurants-postgres-local
    restart: unless-stopped
    environment:
      POSTGRES_DB: restaurants_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - restaurants-network

volumes:
  postgres_data:
    driver: local

networks:
  restaurants-network:
    driver: bridge
